SELECT COUNT(*) AS Categories FROM CATEGORIES;

SELECT COUNT(*) AS Customers FROM CUSTOMERS;

SELECT COUNT(*) AS Employees FROM EMPLOYEES;

SELECT COUNT(*) AS Suppliers FROM SUPPLIERS;

SELECT COUNT(*) AS Products FROM PRODUCTS;

SELECT COUNT(*) AS Orders FROM ORDERS;

SELECT COUNT(*) AS OrderDetails FROM ORDER_DETAILS;

SELECT TOP 5 * FROM EMPLOYEES;

SELECT TOP 1 * FROM PRODUCTS;
GO

SELECT TOP 1 * FROM ORDERS;
GO

SELECT TOP 1 * FROM ORDER_DETAILS;
GO

SELECT TOP 1 * FROM SUPPLIERS;
GO

/*
Question 3
Display male employees whose net salary is >= 8000
*/

SELECT
    EMPLOYEE_int AS Employee_Number,
    FIRST_NAME,
    LAST_NAME,
    DATEDIFF(YEAR, BIRTH_DATE, GETDATE()) AS Age,
    DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS Seniority
FROM EMPLOYEES
WHERE TITLE = 'Mr.'
  AND (SALARY + ISNULL(COMMISSION, 0)) >= 8000
ORDER BY Seniority DESC;